version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: second_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - second_task

  nginx:
    image: nginx:stable-alpine
    container_name: second_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - second_task

  db:
    image: postgres:15
    container_name: second_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: main_user
      POSTGRES_PASSWORD: 1221
    ports:
      - "5432:5432"
    networks:
      - second_task

  db_test:
    image: postgres:15
    container_name: second_db_test
    volumes:
      - db_test_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: 1221
    ports:
      - "5433:5432"
    networks:
      - second_task

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: second_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
      - db_test
    networks:
        - second_task

  rabbitmq:
    image: rabbitmq:4-management
    container_name: second_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
        - second_task

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - './minio_data:/data'
    networks:
        - second_task

networks:
  second_task:
    driver: bridge

volumes:
  db_data:
  db_test_data:
